debugging

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -13,30 +13,16 @@ jobs:
     executor: python-js
     steps:
       - checkout
-      - run: sudo apt-get update
-      # - run:
-      #     name: Install fonts
-      #     command: |
-      #       echo "deb http://ftp.us.debian.org/debian buster main contrib" | sudo tee -a /etc/apt/sources.list
-      #       echo ttf-mscorefonts-installer msttcorefonts/accepted-mscorefonts-eula select true | sudo debconf-set-selections
-      #       sudo apt-get update
-      #       while ! sudo apt-get install ttf-mscorefonts-installer
-      #       do
-      #         echo "Fonts installation failed! Retrying..."
-      #       done
+      - restore_cache:  # caches npm deps based on whether the deps declaration has changed
+          key: deps-{{ checksum "Pipfile.lock" }}-{{ checksum "package-lock.json" }}
       - run:
-          name: Install tor
-          command: sudo apt-get install tor tor-geoipdb
-      # - restore_cache:  # caches npm deps based on whether the deps declaration has changed
-      #     key: deps-{{ checksum "Pipfile.lock" }}-{{ checksum "package-lock.json" }}
-      # - run:
-      #     name: Install project dependencies
-      #     command: pipenv install --dev && npm install
-      # - save_cache:
-      #     key: deps-{{ checksum "Pipfile.lock" }}-{{ checksum "package-lock.json" }}
-      #     paths:
-      #       - ~/.local/share/virtualenvs
-      #       - ./node_modules
+          name: Install project dependencies
+          command: pipenv install --dev && npm install
+      - save_cache:
+          key: deps-{{ checksum "Pipfile.lock" }}-{{ checksum "package-lock.json" }}
+          paths:
+            - ~/.local/share/virtualenvs
+            - ./node_modules
       - persist_to_workspace:
           root: "~"
           paths:
@@ -64,13 +50,17 @@ jobs:
     steps:
       - attach_workspace:
           at: "~"
+      - run:
+          name: Install & start tor
+          command: |
+              sudo apt-get update
+              sudo apt-get install tor tor-geoipdb
+              cp ./tor.cfg ~/.torrc
+              sudo systemctl start tor
       - run: 'date +"%Y-%m-%d" > .today'  # saves today's date to a file so it can be used to expire cache
       - restore_cache:  # caches all HTTP communication of the scrapers for one day
           key: scrapy-{{ checksum ".today" }}
-      # - run: sudo apt-get install tor tor-geoipdb
-      - run: which tor
       - run: |
-          tor -f ./tor.cfg &
           export PROXY_ENABLED=1
           pipenv run fetch
       - save_cache:
@@ -88,6 +78,16 @@ jobs:
   build:
     executor: python-js
     steps:
+      - run:
+          name: Install fonts
+          command: |
+            echo "deb http://ftp.us.debian.org/debian buster main contrib" | sudo tee -a /etc/apt/sources.list
+            echo ttf-mscorefonts-installer msttcorefonts/accepted-mscorefonts-eula select true | sudo debconf-set-selections
+            sudo apt-get update
+            while ! sudo apt-get install ttf-mscorefonts-installer
+            do
+              echo "Fonts installation failed! Retrying..."
+            done
       - attach_workspace:
           at: "~"
       - run: pipenv run build
